# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rst', [dirname(__file__)])
        except ImportError:
            import _rst
            return _rst
        if fp is not None:
            try:
                _mod = imp.load_module('_rst', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rst = swig_import_helper()
    del swig_import_helper
else:
    import _rst
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class constellation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, constellation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, constellation, name)
    __repr__ = _swig_repr
    __swig_setmethods__["s1"] = _rst.constellation_s1_set
    __swig_getmethods__["s1"] = _rst.constellation_s1_get
    if _newclass:
        s1 = _swig_property(_rst.constellation_s1_get, _rst.constellation_s1_set)
    __swig_setmethods__["s2"] = _rst.constellation_s2_set
    __swig_getmethods__["s2"] = _rst.constellation_s2_get
    if _newclass:
        s2 = _swig_property(_rst.constellation_s2_get, _rst.constellation_s2_set)
    __swig_setmethods__["p"] = _rst.constellation_p_set
    __swig_getmethods__["p"] = _rst.constellation_p_get
    if _newclass:
        p = _swig_property(_rst.constellation_p_get, _rst.constellation_p_set)
    __swig_setmethods__["last"] = _rst.constellation_last_set
    __swig_getmethods__["last"] = _rst.constellation_last_get
    if _newclass:
        last = _swig_property(_rst.constellation_last_get, _rst.constellation_last_set)

    def __init__(self):
        this = _rst.new_constellation()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _rst.delete_constellation
    __del__ = lambda self: None
constellation_swigregister = _rst.constellation_swigregister
constellation_swigregister(constellation)

class star(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, star, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, star, name)
    __repr__ = _swig_repr
    __swig_setmethods__["x"] = _rst.star_x_set
    __swig_getmethods__["x"] = _rst.star_x_get
    if _newclass:
        x = _swig_property(_rst.star_x_get, _rst.star_x_set)
    __swig_setmethods__["y"] = _rst.star_y_set
    __swig_getmethods__["y"] = _rst.star_y_get
    if _newclass:
        y = _swig_property(_rst.star_y_get, _rst.star_y_set)
    __swig_setmethods__["z"] = _rst.star_z_set
    __swig_getmethods__["z"] = _rst.star_z_get
    if _newclass:
        z = _swig_property(_rst.star_z_get, _rst.star_z_set)
    __swig_setmethods__["mag"] = _rst.star_mag_set
    __swig_getmethods__["mag"] = _rst.star_mag_get
    if _newclass:
        mag = _swig_property(_rst.star_mag_get, _rst.star_mag_set)
    __swig_setmethods__["starnum"] = _rst.star_starnum_set
    __swig_getmethods__["starnum"] = _rst.star_starnum_get
    if _newclass:
        starnum = _swig_property(_rst.star_starnum_get, _rst.star_starnum_set)
    __swig_setmethods__["magnum"] = _rst.star_magnum_set
    __swig_getmethods__["magnum"] = _rst.star_magnum_get
    if _newclass:
        magnum = _swig_property(_rst.star_magnum_get, _rst.star_magnum_set)
    __swig_setmethods__["id"] = _rst.star_id_set
    __swig_getmethods__["id"] = _rst.star_id_get
    if _newclass:
        id = _swig_property(_rst.star_id_get, _rst.star_id_set)
    __swig_setmethods__["sigma_sq"] = _rst.star_sigma_sq_set
    __swig_getmethods__["sigma_sq"] = _rst.star_sigma_sq_get
    if _newclass:
        sigma_sq = _swig_property(_rst.star_sigma_sq_get, _rst.star_sigma_sq_set)
    __swig_setmethods__["px"] = _rst.star_px_set
    __swig_getmethods__["px"] = _rst.star_px_get
    if _newclass:
        px = _swig_property(_rst.star_px_get, _rst.star_px_set)
    __swig_setmethods__["py"] = _rst.star_py_set
    __swig_getmethods__["py"] = _rst.star_py_get
    if _newclass:
        py = _swig_property(_rst.star_py_get, _rst.star_py_set)

    def __init__(self):
        this = _rst.new_star()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _rst.delete_star
    __del__ = lambda self: None
star_swigregister = _rst.star_swigregister
star_swigregister(star)

class constellation_score(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, constellation_score, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, constellation_score, name)
    __repr__ = _swig_repr
    __swig_setmethods__["totalscore"] = _rst.constellation_score_totalscore_set
    __swig_getmethods__["totalscore"] = _rst.constellation_score_totalscore_get
    if _newclass:
        totalscore = _swig_property(_rst.constellation_score_totalscore_get, _rst.constellation_score_totalscore_set)
    __swig_setmethods__["old_s1"] = _rst.constellation_score_old_s1_set
    __swig_getmethods__["old_s1"] = _rst.constellation_score_old_s1_get
    if _newclass:
        old_s1 = _swig_property(_rst.constellation_score_old_s1_get, _rst.constellation_score_old_s1_set)
    __swig_setmethods__["old_s2"] = _rst.constellation_score_old_s2_set
    __swig_getmethods__["old_s2"] = _rst.constellation_score_old_s2_get
    if _newclass:
        old_s2 = _swig_property(_rst.constellation_score_old_s2_get, _rst.constellation_score_old_s2_set)
    __swig_setmethods__["new_s1"] = _rst.constellation_score_new_s1_set
    __swig_getmethods__["new_s1"] = _rst.constellation_score_new_s1_get
    if _newclass:
        new_s1 = _swig_property(_rst.constellation_score_new_s1_get, _rst.constellation_score_new_s1_set)
    __swig_setmethods__["new_s2"] = _rst.constellation_score_new_s2_set
    __swig_getmethods__["new_s2"] = _rst.constellation_score_new_s2_get
    if _newclass:
        new_s2 = _swig_property(_rst.constellation_score_new_s2_get, _rst.constellation_score_new_s2_set)
    __swig_setmethods__["id_map"] = _rst.constellation_score_id_map_set
    __swig_getmethods__["id_map"] = _rst.constellation_score_id_map_get
    if _newclass:
        id_map = _swig_property(_rst.constellation_score_id_map_get, _rst.constellation_score_id_map_set)
    __swig_setmethods__["scores"] = _rst.constellation_score_scores_set
    __swig_getmethods__["scores"] = _rst.constellation_score_scores_get
    if _newclass:
        scores = _swig_property(_rst.constellation_score_scores_get, _rst.constellation_score_scores_set)

    def __init__(self):
        this = _rst.new_constellation_score()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _rst.delete_constellation_score
    __del__ = lambda self: None
constellation_score_swigregister = _rst.constellation_score_swigregister
constellation_score_swigregister(constellation_score)


def load_db():
    return _rst.load_db()
load_db = _rst.load_db

def compare_mag(s1, s2):
    return _rst.compare_mag(s1, s2)
compare_mag = _rst.compare_mag

def compare_totalscore(cs1, cs2):
    return _rst.compare_totalscore(cs1, cs2)
compare_totalscore = _rst.compare_totalscore

def compare_starnum(s1, s2):
    return _rst.compare_starnum(s1, s2)
compare_starnum = _rst.compare_starnum
class star_query(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, star_query, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, star_query, name)
    __repr__ = _swig_repr
    __swig_setmethods__["oldstars"] = _rst.star_query_oldstars_set
    __swig_getmethods__["oldstars"] = _rst.star_query_oldstars_get
    if _newclass:
        oldstars = _swig_property(_rst.star_query_oldstars_get, _rst.star_query_oldstars_set)
    __swig_setmethods__["newstars"] = _rst.star_query_newstars_set
    __swig_getmethods__["newstars"] = _rst.star_query_newstars_get
    if _newclass:
        newstars = _swig_property(_rst.star_query_newstars_get, _rst.star_query_newstars_set)
    __swig_setmethods__["c_scores"] = _rst.star_query_c_scores_set
    __swig_getmethods__["c_scores"] = _rst.star_query_c_scores_get
    if _newclass:
        c_scores = _swig_property(_rst.star_query_c_scores_get, _rst.star_query_c_scores_set)
    __swig_setmethods__["winner_scores"] = _rst.star_query_winner_scores_set
    __swig_getmethods__["winner_scores"] = _rst.star_query_winner_scores_get
    if _newclass:
        winner_scores = _swig_property(_rst.star_query_winner_scores_get, _rst.star_query_winner_scores_set)
    __swig_setmethods__["winner_id_map"] = _rst.star_query_winner_id_map_set
    __swig_getmethods__["winner_id_map"] = _rst.star_query_winner_id_map_get
    if _newclass:
        winner_id_map = _swig_property(_rst.star_query_winner_id_map_get, _rst.star_query_winner_id_map_set)
    __swig_setmethods__["numoldstars"] = _rst.star_query_numoldstars_set
    __swig_getmethods__["numoldstars"] = _rst.star_query_numoldstars_get
    if _newclass:
        numoldstars = _swig_property(_rst.star_query_numoldstars_get, _rst.star_query_numoldstars_set)
    __swig_setmethods__["numnewstars"] = _rst.star_query_numnewstars_set
    __swig_getmethods__["numnewstars"] = _rst.star_query_numnewstars_get
    if _newclass:
        numnewstars = _swig_property(_rst.star_query_numnewstars_get, _rst.star_query_numnewstars_set)
    __swig_setmethods__["addedoldstars"] = _rst.star_query_addedoldstars_set
    __swig_getmethods__["addedoldstars"] = _rst.star_query_addedoldstars_get
    if _newclass:
        addedoldstars = _swig_property(_rst.star_query_addedoldstars_get, _rst.star_query_addedoldstars_set)
    __swig_setmethods__["addednewstars"] = _rst.star_query_addednewstars_set
    __swig_getmethods__["addednewstars"] = _rst.star_query_addednewstars_get
    if _newclass:
        addednewstars = _swig_property(_rst.star_query_addednewstars_get, _rst.star_query_addednewstars_set)
    __swig_setmethods__["numconst"] = _rst.star_query_numconst_set
    __swig_getmethods__["numconst"] = _rst.star_query_numconst_get
    if _newclass:
        numconst = _swig_property(_rst.star_query_numconst_get, _rst.star_query_numconst_set)
    __swig_setmethods__["mapsize"] = _rst.star_query_mapsize_set
    __swig_getmethods__["mapsize"] = _rst.star_query_mapsize_get
    if _newclass:
        mapsize = _swig_property(_rst.star_query_mapsize_get, _rst.star_query_mapsize_set)
    __swig_setmethods__["dbsize"] = _rst.star_query_dbsize_set
    __swig_getmethods__["dbsize"] = _rst.star_query_dbsize_get
    if _newclass:
        dbsize = _swig_property(_rst.star_query_dbsize_get, _rst.star_query_dbsize_set)
    __swig_setmethods__["map"] = _rst.star_query_map_set
    __swig_getmethods__["map"] = _rst.star_query_map_get
    if _newclass:
        map = _swig_property(_rst.star_query_map_get, _rst.star_query_map_set)
    __swig_setmethods__["img_mask"] = _rst.star_query_img_mask_set
    __swig_getmethods__["img_mask"] = _rst.star_query_img_mask_get
    if _newclass:
        img_mask = _swig_property(_rst.star_query_img_mask_get, _rst.star_query_img_mask_set)
    __swig_setmethods__["starptr"] = _rst.star_query_starptr_set
    __swig_getmethods__["starptr"] = _rst.star_query_starptr_get
    if _newclass:
        starptr = _swig_property(_rst.star_query_starptr_get, _rst.star_query_starptr_set)

    def add_star(self, px, py, mag, newstar):
        return _rst.star_query_add_star(self, px, py, mag, newstar)

    def dist3(self, x1, x2, y1, y2, z1, z2):
        return _rst.star_query_dist3(self, x1, x2, y1, y2, z1, z2)

    def sort_mag(self):
        return _rst.star_query_sort_mag(self)

    def sort_starnum(self):
        return _rst.star_query_sort_starnum(self)

    def add_entry(self, mapidx, curr_const):
        return _rst.star_query_add_entry(self, mapidx, curr_const)

    def search_rel(self):
        return _rst.star_query_search_rel(self)

    def weighted_triad(self, old_s1, old_s2, new_s1, new_s2):
        return _rst.star_query_weighted_triad(self, old_s1, old_s2, new_s1, new_s2)

    def __init__(self):
        this = _rst.new_star_query()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _rst.delete_star_query
    __del__ = lambda self: None
star_query_swigregister = _rst.star_query_swigregister
star_query_swigregister(star_query)
cvar = _rst.cvar

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _rst.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _rst.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _rst.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _rst.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _rst.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _rst.SwigPyIterator_equal(self, x)

    def copy(self):
        return _rst.SwigPyIterator_copy(self)

    def next(self):
        return _rst.SwigPyIterator_next(self)

    def __next__(self):
        return _rst.SwigPyIterator___next__(self)

    def previous(self):
        return _rst.SwigPyIterator_previous(self)

    def advance(self, n):
        return _rst.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _rst.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _rst.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _rst.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _rst.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _rst.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _rst.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _rst.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorStars(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorStars, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorStars, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _rst.VectorStars_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rst.VectorStars___nonzero__(self)

    def __bool__(self):
        return _rst.VectorStars___bool__(self)

    def __len__(self):
        return _rst.VectorStars___len__(self)

    def __getslice__(self, i, j):
        return _rst.VectorStars___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rst.VectorStars___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rst.VectorStars___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rst.VectorStars___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rst.VectorStars___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rst.VectorStars___setitem__(self, *args)

    def pop(self):
        return _rst.VectorStars_pop(self)

    def append(self, x):
        return _rst.VectorStars_append(self, x)

    def empty(self):
        return _rst.VectorStars_empty(self)

    def size(self):
        return _rst.VectorStars_size(self)

    def swap(self, v):
        return _rst.VectorStars_swap(self, v)

    def begin(self):
        return _rst.VectorStars_begin(self)

    def end(self):
        return _rst.VectorStars_end(self)

    def rbegin(self):
        return _rst.VectorStars_rbegin(self)

    def rend(self):
        return _rst.VectorStars_rend(self)

    def clear(self):
        return _rst.VectorStars_clear(self)

    def get_allocator(self):
        return _rst.VectorStars_get_allocator(self)

    def pop_back(self):
        return _rst.VectorStars_pop_back(self)

    def erase(self, *args):
        return _rst.VectorStars_erase(self, *args)

    def __init__(self, *args):
        this = _rst.new_VectorStars(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _rst.VectorStars_push_back(self, x)

    def front(self):
        return _rst.VectorStars_front(self)

    def back(self):
        return _rst.VectorStars_back(self)

    def assign(self, n, x):
        return _rst.VectorStars_assign(self, n, x)

    def resize(self, *args):
        return _rst.VectorStars_resize(self, *args)

    def insert(self, *args):
        return _rst.VectorStars_insert(self, *args)

    def reserve(self, n):
        return _rst.VectorStars_reserve(self, n)

    def capacity(self):
        return _rst.VectorStars_capacity(self)
    __swig_destroy__ = _rst.delete_VectorStars
    __del__ = lambda self: None
VectorStars_swigregister = _rst.VectorStars_swigregister
VectorStars_swigregister(VectorStars)

class VectorInts(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorInts, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorInts, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _rst.VectorInts_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rst.VectorInts___nonzero__(self)

    def __bool__(self):
        return _rst.VectorInts___bool__(self)

    def __len__(self):
        return _rst.VectorInts___len__(self)

    def __getslice__(self, i, j):
        return _rst.VectorInts___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rst.VectorInts___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rst.VectorInts___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rst.VectorInts___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rst.VectorInts___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rst.VectorInts___setitem__(self, *args)

    def pop(self):
        return _rst.VectorInts_pop(self)

    def append(self, x):
        return _rst.VectorInts_append(self, x)

    def empty(self):
        return _rst.VectorInts_empty(self)

    def size(self):
        return _rst.VectorInts_size(self)

    def swap(self, v):
        return _rst.VectorInts_swap(self, v)

    def begin(self):
        return _rst.VectorInts_begin(self)

    def end(self):
        return _rst.VectorInts_end(self)

    def rbegin(self):
        return _rst.VectorInts_rbegin(self)

    def rend(self):
        return _rst.VectorInts_rend(self)

    def clear(self):
        return _rst.VectorInts_clear(self)

    def get_allocator(self):
        return _rst.VectorInts_get_allocator(self)

    def pop_back(self):
        return _rst.VectorInts_pop_back(self)

    def erase(self, *args):
        return _rst.VectorInts_erase(self, *args)

    def __init__(self, *args):
        this = _rst.new_VectorInts(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _rst.VectorInts_push_back(self, x)

    def front(self):
        return _rst.VectorInts_front(self)

    def back(self):
        return _rst.VectorInts_back(self)

    def assign(self, n, x):
        return _rst.VectorInts_assign(self, n, x)

    def resize(self, *args):
        return _rst.VectorInts_resize(self, *args)

    def insert(self, *args):
        return _rst.VectorInts_insert(self, *args)

    def reserve(self, n):
        return _rst.VectorInts_reserve(self, n)

    def capacity(self):
        return _rst.VectorInts_capacity(self)
    __swig_destroy__ = _rst.delete_VectorInts
    __del__ = lambda self: None
VectorInts_swigregister = _rst.VectorInts_swigregister
VectorInts_swigregister(VectorInts)

class VectorDoubles(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorDoubles, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorDoubles, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _rst.VectorDoubles_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _rst.VectorDoubles___nonzero__(self)

    def __bool__(self):
        return _rst.VectorDoubles___bool__(self)

    def __len__(self):
        return _rst.VectorDoubles___len__(self)

    def __getslice__(self, i, j):
        return _rst.VectorDoubles___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _rst.VectorDoubles___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _rst.VectorDoubles___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _rst.VectorDoubles___delitem__(self, *args)

    def __getitem__(self, *args):
        return _rst.VectorDoubles___getitem__(self, *args)

    def __setitem__(self, *args):
        return _rst.VectorDoubles___setitem__(self, *args)

    def pop(self):
        return _rst.VectorDoubles_pop(self)

    def append(self, x):
        return _rst.VectorDoubles_append(self, x)

    def empty(self):
        return _rst.VectorDoubles_empty(self)

    def size(self):
        return _rst.VectorDoubles_size(self)

    def swap(self, v):
        return _rst.VectorDoubles_swap(self, v)

    def begin(self):
        return _rst.VectorDoubles_begin(self)

    def end(self):
        return _rst.VectorDoubles_end(self)

    def rbegin(self):
        return _rst.VectorDoubles_rbegin(self)

    def rend(self):
        return _rst.VectorDoubles_rend(self)

    def clear(self):
        return _rst.VectorDoubles_clear(self)

    def get_allocator(self):
        return _rst.VectorDoubles_get_allocator(self)

    def pop_back(self):
        return _rst.VectorDoubles_pop_back(self)

    def erase(self, *args):
        return _rst.VectorDoubles_erase(self, *args)

    def __init__(self, *args):
        this = _rst.new_VectorDoubles(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _rst.VectorDoubles_push_back(self, x)

    def front(self):
        return _rst.VectorDoubles_front(self)

    def back(self):
        return _rst.VectorDoubles_back(self)

    def assign(self, n, x):
        return _rst.VectorDoubles_assign(self, n, x)

    def resize(self, *args):
        return _rst.VectorDoubles_resize(self, *args)

    def insert(self, *args):
        return _rst.VectorDoubles_insert(self, *args)

    def reserve(self, n):
        return _rst.VectorDoubles_reserve(self, n)

    def capacity(self):
        return _rst.VectorDoubles_capacity(self)
    __swig_destroy__ = _rst.delete_VectorDoubles
    __del__ = lambda self: None
VectorDoubles_swigregister = _rst.VectorDoubles_swigregister
VectorDoubles_swigregister(VectorDoubles)

# This file is compatible with both classic and new-style classes.


